name: pyfor_env

channels:
  - conda-forge
dependencies:
  - poppler
  - python=3.6
  - numpy
  - gdal
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - pyqtgraph
  - matplotlib
  - pyopengl
  - numba
  - rasterio
  - libkml
  - geopandas
  - joblib
  - lastools
  - pip:
      - laspy
      - laxpy
      - sphinx_rtd_theme
      - python-coveralls
      - plyfile
